site_name: 'react-challenge'
site-description: 'Docs for react app'
repo_url: https://github.com/divyamakkar26/react-challenge
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'docs/index.md'
